#pragma once

#include <SDL.h>

#define CW_KMOD_NONE		KMOD_NONE
#define CW_KMOD_LSHIFT		KMOD_LSHIFT
#define CW_KMOD_RSHIFT		KMOD_RSHIFT
#define CW_KMOD_LCTRL		KMOD_LCTRL
#define CW_KMOD_RCTRL		KMOD_RCTRL
#define CW_KMOD_LALT		KMOD_LALT
#define CW_KMOD_RALT		KMOD_RALT
#define CW_KMOD_LGUI		KMOD_LGUI
#define CW_KMOD_RGUI		KMOD_RGUI
#define CW_KMOD_NUM			KMOD_NUM
#define CW_KMOD_CAPS		KMOD_CAPS
#define CW_KMOD_MODE		KMOD_MODE
#define CW_KMOD_CTRL		KMOD_CTRL
#define CW_KMOD_SHIFT		KMOD_SHIFT
#define CW_KMOD_ALT			KMOD_ALT
#define CW_KMOD_GUI			KMOD_GUI
#define CW_KMOD_RESERVED	KMOD_RESERVED