#pragma once

#include <SDL.h>

#define CW_MOUSEBUTTON_LEFT		SDL_BUTTON_LEFT
#define CW_MOUSEBUTTON_MIDDLE	SDL_BUTTON_MIDDLE
#define CW_MOUSEBUTTON_RIGHT		SDL_BUTTON_RIGHT
#define CW_MOUSEBUTTON_X1		SDL_BUTTON_X1
#define CW_MOUSEBUTTON_X2		SDL_BUTTON_X2